Adding plugin support
This closes #5 - plugins can do all sorts of tests at any point
This closes #3 - examples are added

diff --git a/mr-fusion b/mr-fusion
--- a/mr-fusion
+++ b/mr-fusion
@@ -15,7 +15,7 @@ build-merge-list() {
 
         for BRANCH in "${UNHANDLED[@]}"; do
             if [[ "$BRANCH" != "$MR_FUSION_BRANCH" ]]; then
-                PARENT_VAR="BRANCHES__${BRANCH}__parent"
+                PARENT_VAR=$(ini-var "$BRANCH" parent)
 
                 if [[ -z "${!PARENT_VAR}" ]] || in-array "${!PARENT_VAR}" "${MERGE_LIST[@]}"; then
                     MERGE_LIST=("${MERGE_LIST[@]}" "$BRANCH")
@@ -90,6 +90,23 @@ Options:
 EOF
 }
 
+encode-string() {
+    local C OUT
+
+    IN="$1"
+    OUT=""
+
+    while [[ "${#IN}" -gt 0 ]]; do
+        C=${IN:0:1}
+        printf -v C "%x" "'$C"
+        OUT="$OUT$C"
+        IN="${IN:1}"
+    done
+
+    echo "$OUT"
+}
+
+
 helpful-termination() {
     echo ""
     echo "Use '$MR_FUSION -h' for help or check out the website."
@@ -122,7 +139,6 @@ hook-run() {
     eval "LIST=(\"\${${VAR}[@]}\")"
 
     if [[ ${#LIST} -eq 0 ]]; then
-        echo "No commands defined for hook: $1"
         return 0
     fi
 
@@ -160,6 +176,20 @@ in-array() {
 
     return 1
 }
+
+
+ini-var() {
+    local VAR
+
+    VAR="INI_BRANCHES__$(encode-string "$1")"
+
+    if [[ ! -z "$2" ]]; then
+        VAR="${VAR}__$(encode-string "$2")"
+    fi
+
+    echo "$VAR"
+}
+
 
 initialize-repository() {
     local BRANCH VAR
@@ -209,21 +239,63 @@ initialize-repository() {
     )
 }
 
+install-plugin() {
+    if ! in-array "$MR_FUSION_BRANCH" "${GIT_BRANCHES[@]}"; then
+        echo "ERROR: Repository is not configured with a '$MR_FUSION_BRANCH' branch"
+        exit 1
+    fi
+
+    (
+        cd "$WORK_DIR"
+
+        if [[ ! -d plugins ]]; then
+            mkdir plugins
+        fi
+
+        cd plugins
+        git checkout "$MR_FUSION_BRANCH"
+        curl -s "https://raw.githubusercontent.com/tests-always-included/mr-fusion/master/plugins/$1" > $1
+        git add "$1"
+        git commit -m "Installing plugin $1"
+
+        if $DRY_RUN; then
+            echo "Not pushing upstream - this is a dry run"
+            exit 0
+        fi
+
+        git push origin "$MR_FUSION_BRANCH"
+        echo "Plugin downloaded and installed: $1"
+    )
+}
+
 load-config() {
+    local OLD_PWD PLUGIN
+
     switch-to-branch "$MR_FUSION_BRANCH"
+    OLD_PWD=$(pwd)
 
-    if [[ -f "$WORK_DIR/config" ]]; then
+    cd "$WORK_DIR"
+
+    if [[ -f config ]]; then
         echo "Loading config file from repository"
-        . "$WORK_DIR/config" "$WORK_DIR"
+        . config
     fi
 
-    if [[ -f "$WORK_DIR/branches.ini" ]]; then
+    if [[ -f branches.ini ]]; then
         echo "Parsing branches.ini"
-        parse-ini "BRANCHES" "$(cat "$WORK_DIR/branches.ini")"
+        parse-ini INI_BRANCHES "$(cat branches.ini)"
     fi
 
+    for PLUGIN in plugins/*; do
+        if [[ -f "$PLUGIN" ]]; then
+            echo "Loading plugin: $PLUGIN"
+            . "$PLUGIN"
+        fi
+    done
+
+    cd "$OLD_PWD"
     echo "Branches that are configured:"
-    show-list "${BRANCHES[@]}"
+    show-list "${INI_BRANCHES[@]}"
     hook-run-or-exit "load-config"
 }
 
@@ -261,7 +333,7 @@ merge-branches() {
     hook-run-or-exit merge-start
 
     for BRANCH in "${MERGE_LIST[@]}"; do
-        PARENT_VAR="BRANCHES__${BRANCH}__parent"
+        PARENT_VAR="$(ini-var "$BRANCH" parent)"
 
         if [[ -z "${!PARENT_VAR}" ]]; then
             echo "Not merging $BRANCH - it has no parent"
@@ -334,7 +406,7 @@ parse-ini() {
         if [[ "${LINE:0:1}" == '[' ]] && [[ "${LINE:${#LINE}-1}" == "]" ]]; then
             LINE=${LINE:1:${#LINE}-2}
             SECTION=$(trim "$LINE")
-            eval "${PREFIX}__${SECTION}=true"
+            eval "${PREFIX}__$(encode-string "$SECTION")=true"
             eval "${PREFIX}=(\"\${${PREFIX}[@]}\" \"\$SECTION\")"
         else
             IFS="="
@@ -344,7 +416,7 @@ parse-ini() {
 
             if [[ ! -z "$KEY" ]]; then
                 VALUE=$(trim "$VALUE")
-                eval "${PREFIX}__${SECTION}__${KEY}=\$VALUE"
+                eval "${PREFIX}__$(encode-string "$SECTION")__$(encode-string "$KEY")=\$VALUE"
             fi
         fi
     done <<< "$2"
@@ -402,14 +474,15 @@ trim() {
     echo "$STR"
 }
 
-BRANCHES=()
 DO_INITIALIZE=false
 DRY_RUN=false
+GET_PLUGIN=
 GIT_AUTHOR_NAME="Mr. Fusion"
 GIT_AUTHOR_EMAIL="mr.fusion@example.com"
 GIT_BRANCHES=()
 GIT_COMMITTER_NAME="Mr. Fusion"
 GIT_COMMITTER_EMAIL="mr.fusion@example.com"
+INI_BRANCHES=()
 MERGE_LIST=()
 MERGES_FAIL=()
 MERGES_GOOD=()
@@ -417,10 +490,9 @@ MR_FUSION=${0##*/}
 MR_FUSION_BRANCH=${MR_FUSION_BRANCH:-mr-fusion}
 MR_FUSION_DIR=${0%%/*}
 MR_FUSION_URL="https://github.com/tests-always-included/mr-fusion"
-VALIDATION_FUNCTIONS=()
 WORK_DIR=
 
-while getopts ":c:hin:" ARG; do
+while getopts ":c:hin:p:" ARG; do
     case "$ARG" in
         c)
             . "$OPTARG"
@@ -440,6 +512,11 @@ while getopts ":c:hin:" ARG; do
         n)
             echo "Enabling DRY_RUN"
             DRY_RUN=true
+            ;;
+
+        p)
+            echo "Will download and install plugin: $OPTARG"
+            GET_PLUGIN=$OPTARG
             ;;
 
         :)
@@ -467,6 +544,11 @@ clone-repository "$1"
 if $DO_INITIALIZE; then
     load-git-branches
     initialize-repository
+    exit
+fi
+
+if [[ ! -z "$GET_PLUGIN" ]]; then
+    install-plugin "$GET_PLUGIN"
     exit
 fi
 
