Using hooks to allow plugins

diff --git a/mr-fusion b/mr-fusion
--- a/mr-fusion
+++ b/mr-fusion
@@ -14,12 +14,14 @@ build-merge-list() {
         STILL_UNHANDLED=()
 
         for BRANCH in "${UNHANDLED[@]}"; do
-            PARENT_VAR="BRANCHES__${BRANCH}__parent"
+            if [[ "$BRANCH" != "$MR_FUSION_BRANCH" ]]; then
+                PARENT_VAR="BRANCHES__${BRANCH}__parent"
 
-            if [[ -z "${!PARENT_VAR}" ]] || in-array "${!PARENT_VAR}" "${MERGE_LIST[@]}"; then
-                MERGE_LIST=("${MERGE_LIST[@]}" "$BRANCH")
-            else
-                STILL_UNHANDLED=("${STILL_UNHANDLED[@]}" "$BRANCH")
+                if [[ -z "${!PARENT_VAR}" ]] || in-array "${!PARENT_VAR}" "${MERGE_LIST[@]}"; then
+                    MERGE_LIST=("${MERGE_LIST[@]}" "$BRANCH")
+                else
+                    STILL_UNHANDLED=("${STILL_UNHANDLED[@]}" "$BRANCH")
+                fi
             fi
         done
 
@@ -59,6 +61,7 @@ clone-repository() {
 
     echo "Cloning the repository"
     git clone "$CLONE_PATH" "$WORK_DIR"
+    hook-run-or-exit clone-repository
 }
 
 configure-git() {
@@ -67,6 +70,7 @@ configure-git() {
         cd "$WORK_DIR"
         git config push.default simple
     )
+    hook-run-or-exit git-config
 }
 
 help-message() {
@@ -83,12 +87,7 @@ Options:
     -c FILE    Load a config file with settings.
     -h         This help message.
     -n         Dry run - display everything but don't push merges to origin.
-    -r NAME    Use a given reporter, especially for CI environments.
-
-Available Reporters:
 EOF
-    echo -n "    "
-    reporter-list
 }
 
 helpful-termination() {
@@ -97,6 +96,56 @@ helpful-termination() {
     echo "$MR_FUSION_URL"
 
     exit 1
+}
+
+hook-add() {
+    local COMMAND VAR
+
+    if [[ $# -lt 2 ]]; then
+        echo "Must specify hook name and command" >&2
+
+        exit 1
+    fi
+
+    VAR="HOOK_$1"
+    VAR=${VAR//-/_}
+    shift
+    printf -v COMMAND "%q " "$@"
+    eval "${VAR}=(\"\${${VAR}[@]}\" \"\${COMMAND:1}\")"
+}
+
+hook-run() {
+    local COMMAND LIST VAR
+
+    VAR="HOOK_$1"
+    VAR=${VAR//-/_}
+    eval "LIST=(\"\${${VAR}[@]}\")"
+
+    if [[ ${#LIST} -eq 0 ]]; then
+        echo "No commands defined for hook: $1"
+        return 0
+    fi
+
+    for COMMAND in "${LIST[@]}"; do
+        eval "$COMMAND" || return 1
+    done
+
+    return 0
+}
+
+hook-run-or-exit() {
+    local OLD_PWD
+
+    OLD_PWD=$(pwd)
+    cd "$WORK_DIR"
+
+    if ! hook-run $1; then
+        echo "ERROR: Problem detected during $1 hook"
+        echo "ERROR: Aborting"
+        exit 1
+    fi
+
+    cd "$OLD_PWD"
 }
 
 in-array() {
@@ -115,15 +164,15 @@ in-array() {
 initialize-repository() {
     local BRANCH VAR
 
-    if in-array "fusion" "${GIT_BRANCHES[@]}"; then
-        echo "ERROR: Repository already has a 'fusion' branch"
+    if in-array "$MR_FUSION_BRANCH" "${GIT_BRANCHES[@]}"; then
+        echo "ERROR: Repository already has a '$MR_FUSION_BRANCH' branch"
         exit 1
     fi
 
     echo "Initializing repository for Mr. Fusion"
     (
         cd "$WORK_DIR"
-        git checkout --orphan fusion
+        git checkout --orphan "$MR_FUSION_BRANCH"
         git rm -rf .
 
         for VAR in GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL; do
@@ -131,9 +180,11 @@ initialize-repository() {
         done
 
         for BRANCH in "${GIT_BRANCHES[@]}"; do
-            echo "[$BRANCH]" >> branches.ini
-            echo "parent=" >> branches.ini
-            echo "" >> branches.ini
+            if [[ "$BRANCH" != "$MR_FUSION_BRANCH" ]]; then
+                echo "[$BRANCH]" >> branches.ini
+                echo "parent=" >> branches.ini
+                echo "" >> branches.ini
+            fi
         done
 
         git add config branches.ini
@@ -163,6 +214,7 @@ load-config() {
 
     echo "Branches that are configured:"
     show-list "${BRANCHES[@]}"
+    hook-run-or-exit "load-config"
 }
 
 load-git-branches() {
@@ -177,7 +229,7 @@ load-git-branches() {
         LINE="$(trim "$LINE")"
         LINE="${LINE//origin\/}"
 
-        if [[ ! -z "$LINE" ]] && [[ "$LINE" != "$MR_FUSION_BRANCH" ]]; then
+        if [[ ! -z "$LINE" ]]; then
             GIT_BRANCHES=("${GIT_BRANCHES[@]}" "$LINE")
         fi
     done <<< "$(
@@ -187,6 +239,7 @@ load-git-branches() {
     IFS=$OLD_IFS
     echo "Branches found:"
     show-list "${GIT_BRANCHES[@]}"
+    hook-run-or-exit "git-branches"
 }
 
 merge-branches() {
@@ -194,6 +247,8 @@ merge-branches() {
 
     MERGES_FAIL=()
     MERGES_GOOD=()
+
+    hook-run-or-exit merge-start
 
     for BRANCH in "${MERGE_LIST[@]}"; do
         PARENT_VAR="BRANCHES__${BRANCH}__parent"
@@ -204,9 +259,11 @@ merge-branches() {
             if ! merge-two-branches "${!PARENT_VAR}" "$BRANCH"; then
                 echo "ERROR: Merge failed"
                 MERGES_FAIL=("${MERGES_FAIL[@]}" "$BRANCH")
+                hook-run-or-exit merge-fail
             else
                 echo "Merge successful"
                 MERGES_GOOD=("${MERGES_GOOD[@]}" "$BRANCH")
+                hook-run-or-exit merge-good
             fi
 
             if ! (
@@ -218,6 +275,8 @@ merge-branches() {
             fi
         fi
     done
+
+    hook-run-or-exit merge-finish
 }
 
 merge-two-branches() {
@@ -225,6 +284,7 @@ merge-two-branches() {
         cd "$WORK_DIR"
 
         switch-to-branch "$BRANCH" || exit 1
+        hook-run-or-exit merge-before
 
         echo "Merging ${!PARENT_VAR} into $BRANCH"
 
@@ -232,6 +292,8 @@ merge-two-branches() {
             echo "ERROR: Unable to merge ${!PARENT_VAR} into $BRANCH"
             exit 1
         fi
+
+        hook-run-or-exit merge-validate
 
         if $DRY_RUN; then
             echo "Not pushing upstream - this is a dry run"
@@ -255,6 +317,10 @@ parse-ini() {
     while read LINE; do
         LINE=$(trim "$LINE")
 
+        # Eliminate comments
+        LINE=${LINE##\#*}
+        LINE=${LINE##;*}
+
         if [[ "${LINE:0:1}" == '[' ]] && [[ "${LINE:${#LINE}-1}" == "]" ]]; then
             LINE=${LINE:1:${#LINE}-2}
             SECTION=$(trim "$LINE")
@@ -274,14 +340,6 @@ parse-ini() {
     done <<< "$2"
 
     IFS=$OLD_IFS
-}
-
-reporter-list() {
-    echo "not done"
-}
-
-reporter-load() {
-    echo "not done - expected to be able to load teamcity"
 }
 
 show-list() {
@@ -310,6 +368,7 @@ switch-to-branch() {
 
         exit 1
     fi
+    hook-run-or-exit switch-branch
 }
 
 trim() {
@@ -333,35 +392,6 @@ trim() {
     echo "$STR"
 }
 
-validate-branch() {
-    if [[ "${#VALIDATION_FUNCTIONS[@]}" -gt 1 ]]; then
-        for NAME in "${VALIDATION_FUNCTIONS[@]}"; do
-            $NAME "$@" || return 1
-        done
-    fi
-
-    return 0
-}
-
-verify-git-branches() {
-    local BRANCH BRANCH_VAR
-
-    echo "Verifying branches are configured"
-
-    # For each git branch, confirm that it is configured.
-    # When not configured, either make a "root" configuration or error.
-    for BRANCH in "${GIT_BRANCHES[@]}"; do
-        BRANCH_VAR="BRANCHES__$BRANCH"
-
-        if ! validate-branch "$BRANCH" "$BRANCH_VAR"; then
-            echo "ERROR: Branch did not pass validations: $BRANCH"
-            echo "ERROR: Aborting merge"
-
-            exit 1
-        fi
-    done
-}
-
 BRANCHES=()
 DO_INITIALIZE=false
 DRY_RUN=false
@@ -380,7 +410,7 @@ MR_FUSION_URL="https://github.com/tests-always-included/mr-fusion"
 VALIDATION_FUNCTIONS=()
 WORK_DIR=
 
-while getopts ":c:hinr:" ARG; do
+while getopts ":c:hin:" ARG; do
     case "$ARG" in
         c)
             . "$OPTARG"
@@ -400,10 +430,6 @@ while getopts ":c:hinr:" ARG; do
         n)
             echo "Enabling DRY_RUN"
             DRY_RUN=true
-            ;;
-
-        r)
-            reporter-load "$OPTARG"
             ;;
 
         :)
@@ -437,7 +463,6 @@ fi
 load-config
 configure-git
 load-git-branches
-verify-git-branches
 build-merge-list
 merge-branches
 show-results
