Fixing reporting of failed test cases

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -1,29 +1,30 @@
 #!/bin/bash
 set -e
 
+run-suite() {
+    echo "Test suite:  $TEST"
+    echo ""
+
+    ./tester $TEST
+    CODE=$?
+
+    echo ""
+    return $CODE
+}
+
 cd "${0%/*}"
-PASS=0
-FAIL=0
 IFS=$'\n'
-FINAL_RESULT=0
+FAILURES=false
 
-find . -type f -name \*.test | while read TEST; do
-    if (
-        echo "Test suite:  $TEST"
-        echo ""
-
-        ./tester $TEST
-
-        echo ""
-    ); then
-        PASS=$(($PASS + 1))
-    else
-        FAIL=$(($FAIL + 1))
-        FINAL_RESULT=1
+while read TEST; do
+    if ! run-suite "$TEST"; then
+        FAILURES=true
     fi
-done
+done < <(find . -type f -name \*.test)
 
-echo ""
-echo "Pass:  $PASS"
-echo "Fail:  $FAIL"
-exit $FINAL_RESULT
+if $FAILURES; then
+    echo "Failures detected"
+    exit 1
+fi
+
+echo "Test suites all passed"
